services:
  bot:
    build: .
    container_name: max-act-bot
    restart: unless-stopped
    ports:
      - "127.0.0.1:3004:3000"
    env_file:
      - .env
    environment:
      TZ: ${APP_TIMEZONE:-Europe/Moscow}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-net
    volumes:
      - ./storage:/app/storage
      - ./template:/app/template:ro

  worker:
    build: .
    container_name: max-act-worker
    restart: unless-stopped
    command: sh -c "node dist/db/migrate.js && node dist/worker/index.js"
    env_file:
      - .env
    environment:
      TZ: ${APP_TIMEZONE:-Europe/Moscow}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-net
    volumes:
      - ./storage:/app/storage
      - ./template:/app/template:ro

  cleanup-worker:
    build: .
    container_name: max-act-cleanup-worker
    restart: unless-stopped
    command: sh -c "node dist/worker/storage-cleanup.worker.js"
    env_file:
      - .env
    environment:
      TZ: ${APP_TIMEZONE:-Europe/Moscow}
    networks:
      - app-net
    volumes:
      - ./storage:/app/storage

  postgres:
    image: postgres:16-alpine
    container_name: max-act-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${APP_TIMEZONE:-Europe/Moscow}
    command: ["postgres", "-c", "timezone=${APP_TIMEZONE:-Europe/Moscow}", "-c", "log_timezone=${APP_TIMEZONE:-Europe/Moscow}"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:9.13
    container_name: max-act-pgadmin
    restart: unless-stopped
    ports:
      - "127.0.0.1:5052:5050"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 5050
      TZ: ${APP_TIMEZONE:-Europe/Moscow}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-net
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  app-net:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:

